// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: protos/donors-service/donors-service.proto

package donorspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DonorsService_CreateDonor_FullMethodName      = "/DonorsService/CreateDonor"
	DonorsService_GetDonorById_FullMethodName     = "/DonorsService/GetDonorById"
	DonorsService_ListDonors_FullMethodName       = "/DonorsService/ListDonors"
	DonorsService_UpdateDonor_FullMethodName      = "/DonorsService/UpdateDonor"
	DonorsService_DeleteDonor_FullMethodName      = "/DonorsService/DeleteDonor"
	DonorsService_RegisterDonation_FullMethodName = "/DonorsService/RegisterDonation"
	DonorsService_RegisterCheckup_FullMethodName  = "/DonorsService/RegisterCheckup"
)

// DonorsServiceClient is the client API for DonorsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------- Service ----------------
type DonorsServiceClient interface {
	// Donor
	CreateDonor(ctx context.Context, in *CreateDonorRequest, opts ...grpc.CallOption) (*CreateDonorResponse, error)
	GetDonorById(ctx context.Context, in *GetDonorByIdRequest, opts ...grpc.CallOption) (*GetDonorByIdResponse, error)
	ListDonors(ctx context.Context, in *ListDonorsRequest, opts ...grpc.CallOption) (*ListDonorsResponse, error)
	UpdateDonor(ctx context.Context, in *UpdateDonorRequest, opts ...grpc.CallOption) (*UpdateDonorResponse, error)
	DeleteDonor(ctx context.Context, in *DeleteDonorRequest, opts ...grpc.CallOption) (*DeleteDonorResponse, error)
	// EVENTS
	RegisterDonation(ctx context.Context, in *RegisterDonationRequest, opts ...grpc.CallOption) (*RegisterDonationResponse, error)
	RegisterCheckup(ctx context.Context, in *RegisterCheckupRequest, opts ...grpc.CallOption) (*RegisterCheckupResponse, error)
}

type donorsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDonorsServiceClient(cc grpc.ClientConnInterface) DonorsServiceClient {
	return &donorsServiceClient{cc}
}

func (c *donorsServiceClient) CreateDonor(ctx context.Context, in *CreateDonorRequest, opts ...grpc.CallOption) (*CreateDonorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDonorResponse)
	err := c.cc.Invoke(ctx, DonorsService_CreateDonor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donorsServiceClient) GetDonorById(ctx context.Context, in *GetDonorByIdRequest, opts ...grpc.CallOption) (*GetDonorByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDonorByIdResponse)
	err := c.cc.Invoke(ctx, DonorsService_GetDonorById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donorsServiceClient) ListDonors(ctx context.Context, in *ListDonorsRequest, opts ...grpc.CallOption) (*ListDonorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDonorsResponse)
	err := c.cc.Invoke(ctx, DonorsService_ListDonors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donorsServiceClient) UpdateDonor(ctx context.Context, in *UpdateDonorRequest, opts ...grpc.CallOption) (*UpdateDonorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDonorResponse)
	err := c.cc.Invoke(ctx, DonorsService_UpdateDonor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donorsServiceClient) DeleteDonor(ctx context.Context, in *DeleteDonorRequest, opts ...grpc.CallOption) (*DeleteDonorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDonorResponse)
	err := c.cc.Invoke(ctx, DonorsService_DeleteDonor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donorsServiceClient) RegisterDonation(ctx context.Context, in *RegisterDonationRequest, opts ...grpc.CallOption) (*RegisterDonationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDonationResponse)
	err := c.cc.Invoke(ctx, DonorsService_RegisterDonation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donorsServiceClient) RegisterCheckup(ctx context.Context, in *RegisterCheckupRequest, opts ...grpc.CallOption) (*RegisterCheckupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCheckupResponse)
	err := c.cc.Invoke(ctx, DonorsService_RegisterCheckup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DonorsServiceServer is the server API for DonorsService service.
// All implementations must embed UnimplementedDonorsServiceServer
// for forward compatibility
//
// ---------------- Service ----------------
type DonorsServiceServer interface {
	// Donor
	CreateDonor(context.Context, *CreateDonorRequest) (*CreateDonorResponse, error)
	GetDonorById(context.Context, *GetDonorByIdRequest) (*GetDonorByIdResponse, error)
	ListDonors(context.Context, *ListDonorsRequest) (*ListDonorsResponse, error)
	UpdateDonor(context.Context, *UpdateDonorRequest) (*UpdateDonorResponse, error)
	DeleteDonor(context.Context, *DeleteDonorRequest) (*DeleteDonorResponse, error)
	// EVENTS
	RegisterDonation(context.Context, *RegisterDonationRequest) (*RegisterDonationResponse, error)
	RegisterCheckup(context.Context, *RegisterCheckupRequest) (*RegisterCheckupResponse, error)
	mustEmbedUnimplementedDonorsServiceServer()
}

// UnimplementedDonorsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDonorsServiceServer struct {
}

func (UnimplementedDonorsServiceServer) CreateDonor(context.Context, *CreateDonorRequest) (*CreateDonorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDonor not implemented")
}
func (UnimplementedDonorsServiceServer) GetDonorById(context.Context, *GetDonorByIdRequest) (*GetDonorByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDonorById not implemented")
}
func (UnimplementedDonorsServiceServer) ListDonors(context.Context, *ListDonorsRequest) (*ListDonorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDonors not implemented")
}
func (UnimplementedDonorsServiceServer) UpdateDonor(context.Context, *UpdateDonorRequest) (*UpdateDonorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDonor not implemented")
}
func (UnimplementedDonorsServiceServer) DeleteDonor(context.Context, *DeleteDonorRequest) (*DeleteDonorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDonor not implemented")
}
func (UnimplementedDonorsServiceServer) RegisterDonation(context.Context, *RegisterDonationRequest) (*RegisterDonationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDonation not implemented")
}
func (UnimplementedDonorsServiceServer) RegisterCheckup(context.Context, *RegisterCheckupRequest) (*RegisterCheckupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCheckup not implemented")
}
func (UnimplementedDonorsServiceServer) mustEmbedUnimplementedDonorsServiceServer() {}

// UnsafeDonorsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DonorsServiceServer will
// result in compilation errors.
type UnsafeDonorsServiceServer interface {
	mustEmbedUnimplementedDonorsServiceServer()
}

func RegisterDonorsServiceServer(s grpc.ServiceRegistrar, srv DonorsServiceServer) {
	s.RegisterService(&DonorsService_ServiceDesc, srv)
}

func _DonorsService_CreateDonor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDonorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonorsServiceServer).CreateDonor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonorsService_CreateDonor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonorsServiceServer).CreateDonor(ctx, req.(*CreateDonorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonorsService_GetDonorById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDonorByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonorsServiceServer).GetDonorById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonorsService_GetDonorById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonorsServiceServer).GetDonorById(ctx, req.(*GetDonorByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonorsService_ListDonors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDonorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonorsServiceServer).ListDonors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonorsService_ListDonors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonorsServiceServer).ListDonors(ctx, req.(*ListDonorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonorsService_UpdateDonor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDonorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonorsServiceServer).UpdateDonor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonorsService_UpdateDonor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonorsServiceServer).UpdateDonor(ctx, req.(*UpdateDonorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonorsService_DeleteDonor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDonorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonorsServiceServer).DeleteDonor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonorsService_DeleteDonor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonorsServiceServer).DeleteDonor(ctx, req.(*DeleteDonorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonorsService_RegisterDonation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDonationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonorsServiceServer).RegisterDonation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonorsService_RegisterDonation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonorsServiceServer).RegisterDonation(ctx, req.(*RegisterDonationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonorsService_RegisterCheckup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCheckupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonorsServiceServer).RegisterCheckup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonorsService_RegisterCheckup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonorsServiceServer).RegisterCheckup(ctx, req.(*RegisterCheckupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DonorsService_ServiceDesc is the grpc.ServiceDesc for DonorsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DonorsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DonorsService",
	HandlerType: (*DonorsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDonor",
			Handler:    _DonorsService_CreateDonor_Handler,
		},
		{
			MethodName: "GetDonorById",
			Handler:    _DonorsService_GetDonorById_Handler,
		},
		{
			MethodName: "ListDonors",
			Handler:    _DonorsService_ListDonors_Handler,
		},
		{
			MethodName: "UpdateDonor",
			Handler:    _DonorsService_UpdateDonor_Handler,
		},
		{
			MethodName: "DeleteDonor",
			Handler:    _DonorsService_DeleteDonor_Handler,
		},
		{
			MethodName: "RegisterDonation",
			Handler:    _DonorsService_RegisterDonation_Handler,
		},
		{
			MethodName: "RegisterCheckup",
			Handler:    _DonorsService_RegisterCheckup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/donors-service/donors-service.proto",
}
