// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: protos/pharmacist-service/pharmacist-service.proto

package pharmacistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Medicine category enum
type MedicineCategory int32

const (
	MedicineCategory_MEDICINE_CATEGORY_UNSPECIFIED MedicineCategory = 0 // default
	MedicineCategory_MEDICINE_CATEGORY_ANTIBIOTIC  MedicineCategory = 1 // Antibiotiklar
	MedicineCategory_MEDICINE_CATEGORY_ANALGESIC   MedicineCategory = 2 // Og‘riq qoldiruvchilar
	MedicineCategory_MEDICINE_CATEGORY_ANTIVIRAL   MedicineCategory = 3 // Virusga qarshi
	MedicineCategory_MEDICINE_CATEGORY_VITAMINS    MedicineCategory = 4 // Vitaminlar
	MedicineCategory_MEDICINE_CATEGORY_ANTIFUNGAL  MedicineCategory = 5 // Zamburuglarga qarshi
	MedicineCategory_MEDICINE_CATEGORY_VACCINE     MedicineCategory = 6 // Vaktsinalar
	MedicineCategory_MEDICINE_CATEGORY_OTHER       MedicineCategory = 7 // Boshqa
)

// Enum value maps for MedicineCategory.
var (
	MedicineCategory_name = map[int32]string{
		0: "MEDICINE_CATEGORY_UNSPECIFIED",
		1: "MEDICINE_CATEGORY_ANTIBIOTIC",
		2: "MEDICINE_CATEGORY_ANALGESIC",
		3: "MEDICINE_CATEGORY_ANTIVIRAL",
		4: "MEDICINE_CATEGORY_VITAMINS",
		5: "MEDICINE_CATEGORY_ANTIFUNGAL",
		6: "MEDICINE_CATEGORY_VACCINE",
		7: "MEDICINE_CATEGORY_OTHER",
	}
	MedicineCategory_value = map[string]int32{
		"MEDICINE_CATEGORY_UNSPECIFIED": 0,
		"MEDICINE_CATEGORY_ANTIBIOTIC":  1,
		"MEDICINE_CATEGORY_ANALGESIC":   2,
		"MEDICINE_CATEGORY_ANTIVIRAL":   3,
		"MEDICINE_CATEGORY_VITAMINS":    4,
		"MEDICINE_CATEGORY_ANTIFUNGAL":  5,
		"MEDICINE_CATEGORY_VACCINE":     6,
		"MEDICINE_CATEGORY_OTHER":       7,
	}
)

func (x MedicineCategory) Enum() *MedicineCategory {
	p := new(MedicineCategory)
	*p = x
	return p
}

func (x MedicineCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MedicineCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_pharmacist_service_pharmacist_service_proto_enumTypes[0].Descriptor()
}

func (MedicineCategory) Type() protoreflect.EnumType {
	return &file_protos_pharmacist_service_pharmacist_service_proto_enumTypes[0]
}

func (x MedicineCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MedicineCategory.Descriptor instead.
func (MedicineCategory) EnumDescriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{0}
}

// Medicine status enum
type MedicineStatus int32

const (
	MedicineStatus_MEDICINE_STATUS_UNSPECIFIED  MedicineStatus = 0 // default
	MedicineStatus_MEDICINE_STATUS_AVAILABLE    MedicineStatus = 1
	MedicineStatus_MEDICINE_STATUS_OUT_OF_STOCK MedicineStatus = 2
	MedicineStatus_MEDICINE_STATUS_EXPIRED      MedicineStatus = 3
	MedicineStatus_MEDICINE_STATUS_DISCONTINUED MedicineStatus = 4
)

// Enum value maps for MedicineStatus.
var (
	MedicineStatus_name = map[int32]string{
		0: "MEDICINE_STATUS_UNSPECIFIED",
		1: "MEDICINE_STATUS_AVAILABLE",
		2: "MEDICINE_STATUS_OUT_OF_STOCK",
		3: "MEDICINE_STATUS_EXPIRED",
		4: "MEDICINE_STATUS_DISCONTINUED",
	}
	MedicineStatus_value = map[string]int32{
		"MEDICINE_STATUS_UNSPECIFIED":  0,
		"MEDICINE_STATUS_AVAILABLE":    1,
		"MEDICINE_STATUS_OUT_OF_STOCK": 2,
		"MEDICINE_STATUS_EXPIRED":      3,
		"MEDICINE_STATUS_DISCONTINUED": 4,
	}
)

func (x MedicineStatus) Enum() *MedicineStatus {
	p := new(MedicineStatus)
	*p = x
	return p
}

func (x MedicineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MedicineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_pharmacist_service_pharmacist_service_proto_enumTypes[1].Descriptor()
}

func (MedicineStatus) Type() protoreflect.EnumType {
	return &file_protos_pharmacist_service_pharmacist_service_proto_enumTypes[1]
}

func (x MedicineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MedicineStatus.Descriptor instead.
func (MedicineStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{1}
}

type Medicine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category    MedicineCategory `protobuf:"varint,3,opt,name=category,proto3,enum=MedicineCategory" json:"category,omitempty"`
	Description string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32          `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Company     string           `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	Status      MedicineStatus   `protobuf:"varint,7,opt,name=status,proto3,enum=MedicineStatus" json:"status,omitempty"`
	Timestamps  *Timestamps5     `protobuf:"bytes,8,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
}

func (x *Medicine) Reset() {
	*x = Medicine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Medicine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Medicine) ProtoMessage() {}

func (x *Medicine) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Medicine.ProtoReflect.Descriptor instead.
func (*Medicine) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{0}
}

func (x *Medicine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Medicine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Medicine) GetCategory() MedicineCategory {
	if x != nil {
		return x.Category
	}
	return MedicineCategory_MEDICINE_CATEGORY_UNSPECIFIED
}

func (x *Medicine) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Medicine) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Medicine) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Medicine) GetStatus() MedicineStatus {
	if x != nil {
		return x.Status
	}
	return MedicineStatus_MEDICINE_STATUS_UNSPECIFIED
}

func (x *Medicine) GetTimestamps() *Timestamps5 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

// ---------------- Medicine CRUD ----------------
// CREATE
type CreateMedicineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category    MedicineCategory `protobuf:"varint,2,opt,name=category,proto3,enum=MedicineCategory" json:"category,omitempty"`
	Description string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32          `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Company     string           `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	Status      MedicineStatus   `protobuf:"varint,6,opt,name=status,proto3,enum=MedicineStatus" json:"status,omitempty"`
}

func (x *CreateMedicineRequest) Reset() {
	*x = CreateMedicineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedicineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedicineRequest) ProtoMessage() {}

func (x *CreateMedicineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedicineRequest.ProtoReflect.Descriptor instead.
func (*CreateMedicineRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMedicineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMedicineRequest) GetCategory() MedicineCategory {
	if x != nil {
		return x.Category
	}
	return MedicineCategory_MEDICINE_CATEGORY_UNSPECIFIED
}

func (x *CreateMedicineRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMedicineRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateMedicineRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateMedicineRequest) GetStatus() MedicineStatus {
	if x != nil {
		return x.Status
	}
	return MedicineStatus_MEDICINE_STATUS_UNSPECIFIED
}

type CreateMedicineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medicine *Medicine `protobuf:"bytes,1,opt,name=medicine,proto3" json:"medicine,omitempty"`
}

func (x *CreateMedicineResponse) Reset() {
	*x = CreateMedicineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedicineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedicineResponse) ProtoMessage() {}

func (x *CreateMedicineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedicineResponse.ProtoReflect.Descriptor instead.
func (*CreateMedicineResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMedicineResponse) GetMedicine() *Medicine {
	if x != nil {
		return x.Medicine
	}
	return nil
}

// GET BY ID
type GetMedicineByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMedicineByIdRequest) Reset() {
	*x = GetMedicineByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedicineByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedicineByIdRequest) ProtoMessage() {}

func (x *GetMedicineByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedicineByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMedicineByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMedicineByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMedicineByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medicine *Medicine `protobuf:"bytes,1,opt,name=medicine,proto3" json:"medicine,omitempty"`
}

func (x *GetMedicineByIdResponse) Reset() {
	*x = GetMedicineByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedicineByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedicineByIdResponse) ProtoMessage() {}

func (x *GetMedicineByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedicineByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMedicineByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetMedicineByIdResponse) GetMedicine() *Medicine {
	if x != nil {
		return x.Medicine
	}
	return nil
}

// LIST
type ListMedicinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search string         `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`                      // name, category, company
	Status MedicineStatus `protobuf:"varint,2,opt,name=status,proto3,enum=MedicineStatus" json:"status,omitempty"` // optional filter (available, out_of_stock)
	Page   int32          `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // for pagination
	Limit  int32          `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                       // for pagination
}

func (x *ListMedicinesRequest) Reset() {
	*x = ListMedicinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMedicinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMedicinesRequest) ProtoMessage() {}

func (x *ListMedicinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMedicinesRequest.ProtoReflect.Descriptor instead.
func (*ListMedicinesRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListMedicinesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListMedicinesRequest) GetStatus() MedicineStatus {
	if x != nil {
		return x.Status
	}
	return MedicineStatus_MEDICINE_STATUS_UNSPECIFIED
}

func (x *ListMedicinesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMedicinesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMedicinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medicines  []*Medicine `protobuf:"bytes,1,rep,name=medicines,proto3" json:"medicines,omitempty"`
	TotalCount int32       `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // umumiy soni
}

func (x *ListMedicinesResponse) Reset() {
	*x = ListMedicinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMedicinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMedicinesResponse) ProtoMessage() {}

func (x *ListMedicinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMedicinesResponse.ProtoReflect.Descriptor instead.
func (*ListMedicinesResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListMedicinesResponse) GetMedicines() []*Medicine {
	if x != nil {
		return x.Medicines
	}
	return nil
}

func (x *ListMedicinesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UPDATE
type UpdateMedicineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category    MedicineCategory `protobuf:"varint,3,opt,name=category,proto3,enum=MedicineCategory" json:"category,omitempty"`
	Description string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32          `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Company     string           `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	Status      MedicineStatus   `protobuf:"varint,7,opt,name=status,proto3,enum=MedicineStatus" json:"status,omitempty"`
}

func (x *UpdateMedicineRequest) Reset() {
	*x = UpdateMedicineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedicineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedicineRequest) ProtoMessage() {}

func (x *UpdateMedicineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedicineRequest.ProtoReflect.Descriptor instead.
func (*UpdateMedicineRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMedicineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMedicineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMedicineRequest) GetCategory() MedicineCategory {
	if x != nil {
		return x.Category
	}
	return MedicineCategory_MEDICINE_CATEGORY_UNSPECIFIED
}

func (x *UpdateMedicineRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMedicineRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateMedicineRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateMedicineRequest) GetStatus() MedicineStatus {
	if x != nil {
		return x.Status
	}
	return MedicineStatus_MEDICINE_STATUS_UNSPECIFIED
}

type UpdateMedicineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medicine *Medicine `protobuf:"bytes,1,opt,name=medicine,proto3" json:"medicine,omitempty"`
}

func (x *UpdateMedicineResponse) Reset() {
	*x = UpdateMedicineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedicineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedicineResponse) ProtoMessage() {}

func (x *UpdateMedicineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedicineResponse.ProtoReflect.Descriptor instead.
func (*UpdateMedicineResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMedicineResponse) GetMedicine() *Medicine {
	if x != nil {
		return x.Medicine
	}
	return nil
}

// DELETE
type DeleteMedicineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMedicineRequest) Reset() {
	*x = DeleteMedicineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedicineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedicineRequest) ProtoMessage() {}

func (x *DeleteMedicineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedicineRequest.ProtoReflect.Descriptor instead.
func (*DeleteMedicineRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMedicineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMedicineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 204 = deleted
}

func (x *DeleteMedicineResponse) Reset() {
	*x = DeleteMedicineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedicineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedicineResponse) ProtoMessage() {}

func (x *DeleteMedicineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedicineResponse.ProtoReflect.Descriptor instead.
func (*DeleteMedicineResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMedicineResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Timestamps5 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Timestamps5) Reset() {
	*x = Timestamps5{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamps5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamps5) ProtoMessage() {}

func (x *Timestamps5) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamps5.ProtoReflect.Descriptor instead.
func (*Timestamps5) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{11}
}

func (x *Timestamps5) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Timestamps5) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_protos_pharmacist_service_pharmacist_service_proto protoreflect.FileDescriptor

var file_protos_pharmacist_service_pharmacist_service_proto_rawDesc = []byte{
	0x0a, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63,
	0x69, 0x73, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x68, 0x61, 0x72,
	0x6d, 0x61, 0x63, 0x69, 0x73, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x02, 0x0a, 0x08, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69,
	0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63,
	0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69,
	0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2c, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x73, 0x35, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x22, 0xd5,
	0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x27, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x6d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x40, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x63,
	0x69, 0x6e, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x61, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x09,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xe5, 0x01, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x4d, 0x65, 0x64,
	0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x3f, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x63,
	0x69, 0x6e, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64,
	0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x16,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x83,
	0x01, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x35, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x2a, 0x97, 0x02, 0x0a, 0x10, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x1d, 0x4d, 0x45, 0x44,
	0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c,
	0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52,
	0x59, 0x5f, 0x41, 0x4e, 0x54, 0x49, 0x42, 0x49, 0x4f, 0x54, 0x49, 0x43, 0x10, 0x01, 0x12, 0x1f,
	0x0a, 0x1b, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47,
	0x4f, 0x52, 0x59, 0x5f, 0x41, 0x4e, 0x41, 0x4c, 0x47, 0x45, 0x53, 0x49, 0x43, 0x10, 0x02, 0x12,
	0x1f, 0x0a, 0x1b, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x41, 0x54, 0x45,
	0x47, 0x4f, 0x52, 0x59, 0x5f, 0x41, 0x4e, 0x54, 0x49, 0x56, 0x49, 0x52, 0x41, 0x4c, 0x10, 0x03,
	0x12, 0x1e, 0x0a, 0x1a, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x41, 0x54,
	0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x56, 0x49, 0x54, 0x41, 0x4d, 0x49, 0x4e, 0x53, 0x10, 0x04,
	0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x41, 0x54,
	0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x41, 0x4e, 0x54, 0x49, 0x46, 0x55, 0x4e, 0x47, 0x41, 0x4c,
	0x10, 0x05, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x43,
	0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x56, 0x41, 0x43, 0x43, 0x49, 0x4e, 0x45, 0x10,
	0x06, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x41,
	0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x07, 0x2a, 0xb1,
	0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10,
	0x01, 0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x53, 0x54, 0x4f, 0x43,
	0x4b, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x44,
	0x10, 0x04, 0x32, 0xe2, 0x02, 0x0a, 0x11, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x73,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64,
	0x69, 0x63, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e,
	0x65, 0x73, 0x12, 0x15, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63,
	0x69, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65,
	0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x73, 0x74,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_pharmacist_service_pharmacist_service_proto_rawDescOnce sync.Once
	file_protos_pharmacist_service_pharmacist_service_proto_rawDescData = file_protos_pharmacist_service_pharmacist_service_proto_rawDesc
)

func file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP() []byte {
	file_protos_pharmacist_service_pharmacist_service_proto_rawDescOnce.Do(func() {
		file_protos_pharmacist_service_pharmacist_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_pharmacist_service_pharmacist_service_proto_rawDescData)
	})
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescData
}

var file_protos_pharmacist_service_pharmacist_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_pharmacist_service_pharmacist_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protos_pharmacist_service_pharmacist_service_proto_goTypes = []any{
	(MedicineCategory)(0),           // 0: MedicineCategory
	(MedicineStatus)(0),             // 1: MedicineStatus
	(*Medicine)(nil),                // 2: Medicine
	(*CreateMedicineRequest)(nil),   // 3: CreateMedicineRequest
	(*CreateMedicineResponse)(nil),  // 4: CreateMedicineResponse
	(*GetMedicineByIdRequest)(nil),  // 5: GetMedicineByIdRequest
	(*GetMedicineByIdResponse)(nil), // 6: GetMedicineByIdResponse
	(*ListMedicinesRequest)(nil),    // 7: ListMedicinesRequest
	(*ListMedicinesResponse)(nil),   // 8: ListMedicinesResponse
	(*UpdateMedicineRequest)(nil),   // 9: UpdateMedicineRequest
	(*UpdateMedicineResponse)(nil),  // 10: UpdateMedicineResponse
	(*DeleteMedicineRequest)(nil),   // 11: DeleteMedicineRequest
	(*DeleteMedicineResponse)(nil),  // 12: DeleteMedicineResponse
	(*Timestamps5)(nil),             // 13: Timestamps5
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_protos_pharmacist_service_pharmacist_service_proto_depIdxs = []int32{
	0,  // 0: Medicine.category:type_name -> MedicineCategory
	1,  // 1: Medicine.status:type_name -> MedicineStatus
	13, // 2: Medicine.timestamps:type_name -> Timestamps5
	0,  // 3: CreateMedicineRequest.category:type_name -> MedicineCategory
	1,  // 4: CreateMedicineRequest.status:type_name -> MedicineStatus
	2,  // 5: CreateMedicineResponse.medicine:type_name -> Medicine
	2,  // 6: GetMedicineByIdResponse.medicine:type_name -> Medicine
	1,  // 7: ListMedicinesRequest.status:type_name -> MedicineStatus
	2,  // 8: ListMedicinesResponse.medicines:type_name -> Medicine
	0,  // 9: UpdateMedicineRequest.category:type_name -> MedicineCategory
	1,  // 10: UpdateMedicineRequest.status:type_name -> MedicineStatus
	2,  // 11: UpdateMedicineResponse.medicine:type_name -> Medicine
	14, // 12: Timestamps5.created_at:type_name -> google.protobuf.Timestamp
	14, // 13: Timestamps5.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 14: PharmacistService.CreateMedicine:input_type -> CreateMedicineRequest
	5,  // 15: PharmacistService.GetMedicineById:input_type -> GetMedicineByIdRequest
	7,  // 16: PharmacistService.ListMedicines:input_type -> ListMedicinesRequest
	9,  // 17: PharmacistService.UpdateMedicine:input_type -> UpdateMedicineRequest
	11, // 18: PharmacistService.DeleteMedicine:input_type -> DeleteMedicineRequest
	4,  // 19: PharmacistService.CreateMedicine:output_type -> CreateMedicineResponse
	6,  // 20: PharmacistService.GetMedicineById:output_type -> GetMedicineByIdResponse
	8,  // 21: PharmacistService.ListMedicines:output_type -> ListMedicinesResponse
	10, // 22: PharmacistService.UpdateMedicine:output_type -> UpdateMedicineResponse
	12, // 23: PharmacistService.DeleteMedicine:output_type -> DeleteMedicineResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_pharmacist_service_pharmacist_service_proto_init() }
func file_protos_pharmacist_service_pharmacist_service_proto_init() {
	if File_protos_pharmacist_service_pharmacist_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Medicine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMedicineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMedicineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetMedicineByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetMedicineByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListMedicinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListMedicinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMedicineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMedicineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMedicineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMedicineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Timestamps5); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_pharmacist_service_pharmacist_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_pharmacist_service_pharmacist_service_proto_goTypes,
		DependencyIndexes: file_protos_pharmacist_service_pharmacist_service_proto_depIdxs,
		EnumInfos:         file_protos_pharmacist_service_pharmacist_service_proto_enumTypes,
		MessageInfos:      file_protos_pharmacist_service_pharmacist_service_proto_msgTypes,
	}.Build()
	File_protos_pharmacist_service_pharmacist_service_proto = out.File
	file_protos_pharmacist_service_pharmacist_service_proto_rawDesc = nil
	file_protos_pharmacist_service_pharmacist_service_proto_goTypes = nil
	file_protos_pharmacist_service_pharmacist_service_proto_depIdxs = nil
}
